### ISSUE TITLE
blockType conflict

### ISSUE THREAD

**Issue by dadigu** [oliverfindl/vue-svg-inline-loader#43] opened 2020-07-30 11:41 UTC
I'm having an issue running development mode. I have recently added [Vue Styleguidist](https://github.com/vue-styleguidist/vue-styleguidist) to my project and I use `<docs>` tag in my `.vue` components. Everything works as expected when I build a styleguide, but when I try running development then my build fails. 

Now I have been poking at this and it seems that this loader is the issue, when I remove it then the build succeeds

```
in ./src/common/Forms/InputField.vue?vue&type=custom&index=0&blockType=docs

Module parse failed: Unexpected token (113:3)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
 * ./node_modules/vue-svg-inline-loader/dist/index.min.js
You may need an additional loader to handle the result of these loaders.
|
|
> My docs
|
```

**Comment by oliverfindl** [comment] 2020-07-30 15:36
Hello,

unfortunately I'm not familiar with that package. This loader only replaces marked img tags with contents of svg files. In more detail, it takes `*.vue` file passed to this loader, replaces all marked img tags (maybe you have some in your docs tag, somebody had similar [issue](https://github.com/oliverfindl/vue-svg-inline-loader/issues/33) where this loader replaced content in comments) and pass this processed `*.vue` file to another loader in chain. This loader does not utilize blocks, it parses whole `*.vue` file as string. So if you got it working without this loader, then try manually change one of your `*.vue` files - replace all of those marked img tags with actual contents of that svg file (same thing as this loader does when not using sprite and svgo option). If it breaks at this point, that package probably can't handle svg tags.

Additionally, you can try to change order of your loaders for `*.vue` files, but from your error, it seems, that you have only two of them ([vue-loader](https://github.com/vuejs/vue-loader) and [vue-svg-inline-loader](https://github.com/oliverfindl/vue-svg-inline-loader)) so this won't help, because this configuration should work without problems in all [webpack](https://github.com/webpack/webpack) based projects.

Please let me know if this helps. If this won't help solve your issue, please provide some minimal repo, where this issue would be reproducible with steps how to reproduce it, so I could log and debug input and output from this loader.

Thanks.

**Comment by oliverfindl** [comment] 2020-09-30 15:09
Closing this issue.

**Closed by oliverfindl** 2020-09-30 15:09 UTC
