### ISSUE TITLE
Unexpected Token, expected "," when svg-inline used in object

### ISSUE THREAD

**Issue by gkatsanos** [oliverfindl/vue-svg-inline-loader#29] opened 2019-10-04 07:40 UTC
```js
  data() {
    return {
      tabs: [
        {
          name: this.$t('device_models.tabs.hca'),
          icon: '<img svg-inline src="assets/icons/hca.svg">',
          categories: { meter_type_keys: 'heat_cost_allocator' },
        },
    };
  },
```

```html
        <div class="device-models__tab">
          {{ tab.icon }}
       </div>
```

```
SyntaxError: /Users/gk/repos/mh-platform/app/javascript/manager/components/device-models.vue: Unexpected token, expected "," (47:132)

  45 |           name: this.$t('device_models.tabs.hca'),
  46 |           path: '/device-models/hca',
> 47 |           icon: '<svg width="42" height="42" viewBox="0 0 42 42" fill="none" xmlns="http://www.w3.org/2000/svg" v-bind:svg-inline="''" v-bind:role="'presentation'" v-bind:focusable="'false'" v-bind:tabindex="'-1'"><path d="M0 0h42v42H0V0z" fill="#fff" fill-opacity=".01"/><path d="M0 0h42v42H0V0z" stroke="#fff"/><path fill-rule="evenodd" clip-rule="evenodd" d="M15 3a1 1 0 00-1 1v34a1 1 0 001 1h12a1 1 0 001-1V4a1 1 0 00-1-1H15zm12 6H15v4h12V9zM15 7a1 1 0 112 0 1 1 0 01-2 0zm4-1a1 1 0 100 2 1 1 0 000-2z" fill="#4A4A4A"/><path d="M19 10h1v2h-1v-2zM20.478 10h1v2h-1v-2zM21.957 10h1v2h-1v-2zM23.435 10h1v2h-1v-2zM24.914 10h1v2h-1v-2z" fill="#4A4A4A"/></svg>',
     |                                                                                                                                     ^
  48 |           categories: { meter_type_keys: 'heat_cost_allocator' },
  49 |         },
  50 |         {
```

**Comment by oliverfindl** [comment] 2019-10-04 17:16
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.3.2](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.3.2).

Although, technically it works as expected, [workaround](https://github.com/oliverfindl/vue-svg-inline-loader/issues/2#issuecomment-474304724) (which was never officialy supported by this loader, it was only side effect) with image tag outside template won't work anymore. This is caused by [hotfix](https://github.com/oliverfindl/vue-svg-inline-loader/issues/28) I published yesterday, where attributes from image tag are now binded to svg tag by [Vue bindings](https://vuejs.org/v2/guide/class-and-style.html). This approach won't produce valid raw html output, that can be used with `v-html` directive.

If this behavior breaks your project, please fallback to version 1.3.0. Proper fix would require some code refactoring, but I don't have time for it right now.

Currently I'm working on [Vue](https://github.com/vuejs/vue) plugin version of this loader, where this issue is fixed. When I finish this plugin, I can try to refactor code and backport this feature to loader too.

Thanks

**Comment by oliverfindl** [comment] 2019-10-16 17:50
Closing this issue.

**Closed by oliverfindl** 2019-10-16 17:50 UTC
