### ISSUE TITLE
Why is it remove viewBox attribute?

### ISSUE THREAD

**Issue by fatihhayri** [oliverfindl/vue-svg-inline-loader#9] opened 2018-12-01 13:55 UTC
I added inline svg file.

SVG source:
`````
<svg width="33px" height="31px" viewBox="0 0 33 31" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title>Home</title>....
`````

Add code 

````
<img svg-inline class="icon" src="../assets/icons/home.svg" />
`````

after render 

`````
<svg svg-inline="" role="presentation" focusable="false" width="33" height="31" xmlns="http://www.w3.org/2000/svg" class="icon">
``````
I don't resize SVG  with CSS due to remove viewbox attribute

**Comment by oliverfindl** [comment] 2018-12-01 14:16
Hello.

this loader does not remove any attributes from source SVG by itself. Although `removeAttributes` and `svgo` options might be causing your issue. Please check your configuration.

You can also look at provided [examples](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/examples/README.md). None of these examples (using default loader options) does not suffer with this issue.

If you can not figure out, what is causing this behavior in your project, please provide your configuration file, so I can try to reproduce it.

Thanks

**Comment by Puwka** [comment] 2018-12-10 13:55
Same issue

**Comment by Puwka** [comment] 2018-12-10 14:30
Its svgo bug, [removeViewBox](https://github.com/svg/svgo/blob/master/plugins/removeViewBox.js)
But it doesn't help when I set svgo plugin `removeViewBox` option into false.
I saw fork on this loader where someone removed svgo. Its nice solution cuz I only need img tag to be replaced by svg that I provide, without useless optimization and refactoring.

**Comment by oliverfindl** [comment] 2018-12-10 14:44
Hello,

can you share some dummy project which has this issue replicable? It may be caused by this [svgo issue](https://github.com/svg/svgo/issues/1024).

Anyway, when I will have some spare time, I will make a option to completly disable svgo.

Thanks

**Comment by oliverfindl** [comment] 2018-12-10 19:48
Hello guys,

I modified svgo option. You can set it to`null` or `false` to completely disable [SVGO](https://github.com/svg/svgo).

Still would be glad to see some dummy project which has this issue, because I never encountered it in my projects.

Please give me feedback, if disabling [SVGO](https://github.com/svg/svgo) solved your issues.

Thanks

**Comment by oliverfindl** [comment] 2018-12-11 08:14
Hello again guys,

I probably figured what is causing your issue. With default [SVGO](https://github.com/svg/svgo) configuration, it removes viewBox  attribute if width and height attributes are defined and they are same as coordinates in viewBox attribute ([reference](https://github.com/svg/svgo/blob/master/plugins/removeViewBox.js)).

@Puwka:
I just tested disabling [SVGO](https://github.com/svg/svgo) removeViewBox plugin, and it preserved viewBox attribute as expected. So probably you had something wrong in your [SVGO](https://github.com/svg/svgo) configuration.
This loader configuration works for me:
```javascript
{
	loader: "vue-svg-inline-loader",
	options: { svgo: { plugins: [ { removeViewBox: false } ] } }
}
```

I will update default svgo configuration option of loader at evening.

Hope this helps.

**Comment by Puwka** [comment] 2018-12-11 08:16
Sorry mate, was sleeping, forgot to answer you.
Actually it works ok like this:
`{
	loader: "vue-svg-inline-loader",
	options: { svgo: { plugins: [ { removeViewBox: false } ] } }
}`

I have complex webpack config, so I need to paste it into two places, but for other users it should work perfect

**Comment by oliverfindl** [comment] 2018-12-19 07:52
Week without any responses.

Closing this issue.

**Comment by hacknug** [comment] 2019-02-06 18:21
Hey @oliverfindl, I'm using your plugin for the first time and it looks like it's still stripping the viewBox attribute no matter what. I've tried explicitly setting the options to `{ svgo: { plugins: [ { removeViewBox: false } ] } }` with no luck.

Here's a [link to the repo](https://github.com/hacknug/klayaya) and another one to [the preview site](https://klayaya.netlify.com/) in case it is of any help.

**Comment by oliverfindl** [comment] 2019-02-06 19:37
Hello,

I identified issue as svg attributes not being used in svg symbol itself, but in referencing svg. I will try fix it this weekend.

As workaround you can use loader without using `svg-sprite` directive. Anyway, its only useful, when you use same svg multiple times per component.

So far thanks for reporting. I will respond to this thread when fixed version is online at npm.

**Comment by hacknug** [comment] 2019-02-06 19:52
@oliverfindl thanks!

**Comment by oliverfindl** [comment] 2019-02-09 15:08
Hello guys,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.2.11](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.2.11).

You will probably have to fiddle with your CSS and/or with SVG dimensions if you are using `svg-sprite` directive.

Please give me feedback if it works as expected.

Thanks

**Comment by oliverfindl** [comment] 2019-03-01 06:13
Closing this issue.

**Closed by oliverfindl** 2019-03-01 06:13 UTC
